#!/usr/bin/env bash
# This script installs the NGINX web server on my local server

sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo echo "Hello World!" | sudo tee /var/www/html/index.html
sudo service nginx restart
