#!/usr/bin/env bash
# install load balancer
sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-1.7
sudo apt-get -y update
sudo apt-get -y install haproxy
sudo echo -e "\nlisten www" >> /etc/haproxy/haproxy.cfg
sudo echo -e "\tbind :80" >> /etc/haproxy/haproxy.cfg
sudo echo -e "\tbalance roundrobin" >> /etc/haproxy/haproxy.cfg
sudo echo -e "\tserver 13102-web-01 100.25.170.76" >> /etc/haproxy/haproxy.cfg
sudo echo -e "\tserver 13102-web-02 34.224.5.9" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
