#!/usr/bin/env bash
# Installs UFW firewall and configure some rules

# Update packages
sudo apt-get update

# Install UFW firewall
sudo apt-get install ufw

# Enable firewall
sudo ufw enable

# Set default configurations
sudo ufw default deny incoming

# Allow incoming traffic through specific ports
sudo ufw allow 22/tcp
sudo ufw allow 80/tcp
sudo ufw allow 443/tcp

# Enable ufw to enforce custom rules
sudo ufw enable

# Check ufw status
sudo ufw status
